[package]
name = "nft_contract"
version = "0.1.0"
edition = "2018"

[dependencies]
ink_lang = "3.0.0"
ink_storage = "3.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["std"]
std = [
    "ink_lang/std",
    "ink_storage/std",
]